### ISSUE TITLE
How about using Meetup API?

### ISSUE THREAD

**Issue by SebastienFCT** [learn-swift-winnipeg/Meetup-Project#2]
Should we be using [Meetup API](https://www.meetup.com/meetup_api/) for the project or are we going to "duplicate" the content of our meetups in our own remote system (the swift server)?

**Comment by jeffreyfultonca** [comment]
@SebastienFCT I would like us to gain experience using a database in our Swift server project, so to that end I guess I’m voting we “duplicate” the content. However it could also be cool to pull some data from the Meetup.com API as well. Then we get experience with server-to-server communication and automated tasks too.

**Comment by spprichard** [comment]
Yea so I think we will use a combination approach. There are things the Meetup API exposes that we may want to integrate into out service. There are also things that we will want to store as well. For example comments a specific User left on a topic.

**Comment by SebastienFCT** [comment]
Sounds good to me and makes sense. 

I'm closing the ticket,

We should document this somehow, and make sure that these two providers will be clearly identified in the mobile app (while reading the code, you should know which API you're actually consuming).
