### ISSUE TITLE
CI Solution is a Problem

### ISSUE THREAD

**Issue by spprichard** [learn-swift-winnipeg/Meetup-Project#29]
So, after investigating how to integrate CircleCI into the Backend Project. I found that we must have a MacOS plan. Unless I am missing something, CircleCI won't work for building, testing, deploying the Backend project. We would have to pay $39 per month. 

However, it appears that TravisCI could work. I am exploring that option now. So questions

@SebastienFCT have you found a way to build a linux project with CircleCI?

What am I missing for building the Backend project? (Check the build logs in CircleCI)

How do we feel about possible having 2 different CI's?

**Comment by SebastienFCT** [comment]
I had to contact their team but they basically gave us access to a free tier for MacOS.

It worked once and then it stopped and I was already working on something else. I'll contact them this week and try to troubleshoot with them.

So CirclyCI should be a viable option for our project still :)

**Comment by spprichard** [comment]
Ok, if that is the case I am good with CircleCI. Let me know how that goes. I would like to have CI set up before the next meet up

**Comment by spprichard** [comment]
@SebastienFCT any news?

**Comment by SebastienFCT** [comment]
Contacted them, I'll update the repo and test the scan as soon as I get back from them

**Comment by spprichard** [comment]
Sooooo, for the backend...I found a way to not need a macOS plan

**Comment by spprichard** [comment]
There is a setting in the project that specifies what hardware to run the builds on. I think we may be headed down a path where we split up the backend and the iOS app. I think having them live in the same project is a bad idea (in the context of keeping CI configured)

**Comment by spprichard** [comment]
I am going to try to see if we can specify 2 different CI configs....

**Comment by SebastienFCT** [comment]
I believe you're right :)

**Comment by SebastienFCT** [comment]
By the way I'm testing now, it should have been fixed

**Comment by SebastienFCT** [comment]
I confirm it has been fixed. (it reports that there was no test but that another ticket!)
