### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by spprichard** [learn-swift-winnipeg/Meetup-Project#30]
How do we feel about creating a Slack Team for the Learn Swift Winnipeg Meetup Group? I know I use Slack a lot for work, and other groups. What does everyone else use? Another option could be Discord.

My though is that we need a way to post questions, discuss things, chat privately, etc. Thoughts?

**Comment by SebastienFCT** [comment]
I'm not using slack, but I feel like we should probably wait and see if we get more participants on this project!

**Comment by SebastienFCT** [comment]
Taking back what I said, I realize that no matter how many people are working on the project, github doesn't really provide any quick way to communicate!

**Comment by spprichard** [comment]
We created a slack! it can be found [here](learnswiftwinnipeg.slack.com). Closing issue
