### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by SebastienFCT** [learn-swift-winnipeg/Meetup-Project#5]
While Steven suggested that every pull request should be peer reviewed by at least two other developers, we should integrate CI to our repository because
* It's saves time and prevent escaped syntax issues
* It's something we should be familiar with as developers

- [x] Research CI solutions ([Travis](https://travis-ci.org/), [Jenkins](https://jenkins.io/), etc.)
- [x] Setup CI for the repository

**Comment by spprichard** [comment]
Circle CI?
